version: '3.8'

services:
  osrm-backend-car:
    image: ghcr.io/project-osrm/osrm-backend:v26.5.0-amd64-debian
    container_name: osrm-backend-car
    ports:
      - "5000:5000"
    volumes:
      - "/opt/oms/omeye/omeye-hss/.docker/osrm/pbf:/data"
    command: osrm-routed --algorithm mld /data/south-korea.osrm
    networks:
      - osrm-network
    tty: true
    stdin_open: true
  osrm-backend-foot:
    image: ghcr.io/project-osrm/osrm-backend:v26.5.0-amd64-debian
    container_name: osrm-backend-foot
    ports:
      - "5001:5000"
    volumes:
      - "/opt/oms/omeye/omeye-hss/.docker/osrm/pbf:/data"
    command: osrm-routed --algorithm mld /data/south-korea.osrm
    networks:
      - osrm-network
    tty: true
    stdin_open: true

  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim
    ports:
      - "5002:8080"
    volumes:
      - "/opt/oms/omeye/omeye-hss/.docker/osrm/pbf:/data"
    #  - "/opt/oms/omeye/.docker/osrm/nominatim/postgresql.conf:/etc/postgresql/postgresql.conf"
    #command: bash -c "cp /etc/postgresql/postgresql.conf /var/lib/postgresql/16/main/postgresql.conf && /app/start.sh"
    environment:
      - PBF_URL=file:///data/south-korea.osm.pbf
      - NOMINATIM_QUERY_POOL_SIZE=10
      - NOMINATIM_THREADS=32
      - THREADS=64
      - GUNICORN_WORKERS=64
    networks:
      - osrm-network
    tty: true
    stdin_open: true

networks:
  osrm-network:
    driver: bridge
